export enum UserRole {
    USER = 'USER',
    MANAGER = 'MANAGER',
    ADMIN = 'ADMIN',
    NewUser = 'NewUser',
    PRODO = 'PRODO',
    PRODO_ADMIN="PRODO_ADMIN",
    CLIENT = 'CLIENT',
    MANUFACTURER = 'MANUFACTURER',
    SUPPLIER = 'SUPPLIER',
    LOGISTICS = 'LOGISTICS',
    UnimoveStoreManager = 'UnimoveStoreManager',
    UnimoveAdmin = 'UnimoveAdmin',
    UnimoveSuperAdmin = 'UnimoveSuperAdmin',
    createRFQ="createRFQ"
}
 
export enum Permission {
        generateInvoice = 'generateInvoice',
        generatePayment = 'generatePayment',
        generatePurchaseOrder = 'generatePurchaseOrder',
        generateQuotation = 'generateQuotation',
        generateOrder = 'generateOrder',
        generateQuotationFromRFQ = 'generateQuotationFromRFQ',
        generateOrderFromRFQ = 'generateOrderFromRFQ',
        generateInvoiceFromRFQ = 'generateInvoiceFromRFQ',
        generatePaymentFromRFQ = 'generatePaymentFromRFQ',
        generatePurchaseOrderFromRFQ = 'generatePurchaseOrderFromRFQ',
        generateQuotationFromOrder = 'generateQuotationFromOrder',
        uploadRFQ = 'uploadRFQ',
        uploadQuotation = 'uploadQuotation',
        uploadOrder = 'uploadOrder',
        uploadInvoice = 'uploadInvoice',
        uploadPayment = 'uploadPayment',
        uploadPurchaseOrder = 'uploadPurchaseOrder',
        uploadQuotationFromRFQ = 'uploadQuotationFromRFQ',
        uploadOrderFromRFQ = 'uploadOrderFromRFQ',
        uploadInvoiceFromRFQ = 'uploadInvoiceFromRFQ',
        uploadPaymentFromRFQ = 'uploadPaymentFromRFQ',
        uploadPurchaseOrderFromRFQ = 'uploadPurchaseOrderFromRFQ',
        uploadQuotationFromOrder = 'uploadQuotationFromOrder',
        updateRFQ = 'updateRFQ',
        updateOrder = 'updateOrder',
        updateInvoice = 'updateInvoice',
        updatePayment = 'updatePayment',
        updatePurchaseOrder = 'updatePurchaseOrder',
        updateQuotation = 'updateQuotation',
        updateQuotationFromRFQ = 'updateQuotationFromRFQ',
        updateOrderFromRFQ = 'updateOrderFromRFQ',
        updateInvoiceFromRFQ = 'updateInvoiceFromRFQ',
        updatePaymentFromRFQ = 'updatePaymentFromRFQ',
        updatePurchaseOrderFromRFQ = 'updatePurchaseOrderFromRFQ',
        updateQuotationFromOrder = 'updateQuotationFromOrder',
        deleteRFQ = 'deleteRFQ',
        deleteOrder = 'deleteOrder',
        deleteInvoice = 'deleteInvoice',
        deletePayment = 'deletePayment',
        deletePurchaseOrder = 'deletePurchaseOrder',
        deleteQuotation = 'deleteQuotation',
        deleteQuotationFromRFQ = 'deleteQuotationFromRFQ',
        deleteOrderFromRFQ = 'deleteOrderFromRFQ',
        deleteInvoiceFromRFQ = 'deleteInvoiceFromRFQ',
        deletePaymentFromRFQ = 'deletePaymentFromRFQ',
        deletePurchaseOrderFromRFQ = 'deletePurchaseOrderFromRFQ',
        deleteQuotationFromOrder = 'deleteQuotationFromOrder',
        acceptRFQ = 'acceptRFQ',
        acceptOrder = 'acceptOrder',
        acceptInvoice = 'acceptInvoice',
        acceptPayment = 'acceptPayment',
        acceptPurchaseOrder = 'acceptPurchaseOrder',
        acceptQuotation = 'acceptQuotation',
        acceptQuotationFromRFQ = 'acceptQuotationFromRFQ',
        acceptOrderFromRFQ = 'acceptOrderFromRFQ',
        acceptInvoiceFromRFQ = 'acceptInvoiceFromRFQ',
        acceptPaymentFromRFQ = 'acceptPaymentFromRFQ',
        acceptPurchaseOrderFromRFQ = 'acceptPurchaseOrderFromRFQ',
        acceptQuotationFromOrder = 'acceptQuotationFromOrder',
        rejectRFQ = 'rejectRFQ',
        rejectOrder = 'rejectOrder',
        rejectInvoice = 'rejectInvoice',
        rejectPayment = 'rejectPayment',
        rejectPurchaseOrder = 'rejectPurchaseOrder',
        rejectQuotation = 'rejectQuotation',
        rejectQuotationFromRFQ = 'rejectQuotationFromRFQ',
        rejectOrderFromRFQ = 'rejectOrderFromRFQ',
        rejectInvoiceFromRFQ = 'rejectInvoiceFromRFQ',
        rejectPaymentFromRFQ = 'rejectPaymentFromRFQ',
        rejectPurchaseOrderFromRFQ = 'rejectPurchaseOrderFromRFQ',
        rejectQuotationFromOrder = 'rejectQuotationFromOrder',
        sendRFQ = 'sendRFQ',
        sendOrder = 'sendOrder',
        sendInvoice = 'sendInvoice',
        sendPayment = 'sendPayment',
        sendPurchaseOrder = 'sendPurchaseOrder',
        sendQuotation = 'sendQuotation',
        sendQuotationFromRFQ = 'sendQuotationFromRFQ',
        sendOrderFromRFQ = 'sendOrderFromRFQ',
        sendInvoiceFromRFQ = 'sendInvoiceFromRFQ',
        sendPaymentFromRFQ = 'sendPaymentFromRFQ',
        sendPurchaseOrderFromRFQ = 'sendPurchaseOrderFromRFQ',
        sendQuotationFromOrder = 'sendQuotationFromOrder',
        receiveRFQ = 'receiveRFQ',
        receiveOrder = 'receiveOrder',
        receiveInvoice = 'receiveInvoice',
        receivePayment = 'receivePayment',
        receivePurchaseOrder = 'receivePurchaseOrder',
        receiveQuotation = 'receiveQuotation',
        receiveQuotationFromRFQ = 'receiveQuotationFromRFQ',
        receiveOrderFromRFQ = 'receiveOrderFromRFQ',
        receiveInvoiceFromRFQ = 'receiveInvoiceFromRFQ',
        receivePaymentFromRFQ = 'receivePaymentFromRFQ',
        receivePurchaseOrderFromRFQ = 'receivePurchaseOrderFromRFQ',
        receiveQuotationFromOrder = 'receiveQuotationFromOrder',
        shipRFQ = 'shipRFQ',
        shipOrder = 'shipOrder',
        shipInvoice = 'shipInvoice',
        shipPayment = 'shipPayment',
        shipPurchaseOrder = 'shipPurchaseOrder',
        shipQuotation = 'shipQuotation',
        shipQuotationFromRFQ = 'shipQuotationFromRFQ',
        shipOrderFromRFQ = 'shipOrderFromRFQ',
        shipInvoiceFromRFQ = 'shipInvoiceFromRFQ',
        shipPaymentFromRFQ = 'shipPaymentFromRFQ',

        shipPurchaseOrderFromRFQ = 'shipPurchaseOrderFromRFQ',
        shipQuotationFromOrder = 'shipQuotationFromOrder',
        deliverRFQ = 'deliverRFQ',
        deliverOrder = 'deliverOrder',
        deliverInvoice = 'deliverInvoice',
        deliverPayment = 'deliverPayment',
        deliverPurchaseOrder = 'deliverPurchaseOrder',
        deliverQuotation = 'deliverQuotation',
        deliverQuotationFromRFQ = 'deliverQuotationFromRFQ',
        deliverOrderFromRFQ = 'deliverOrderFromRFQ',
        deliverInvoiceFromRFQ = 'deliverInvoiceFromRFQ',
        deliverPaymentFromRFQ = 'deliverPaymentFromRFQ',
        deliverPurchaseOrderFromRFQ = 'deliverPurchaseOrderFromRFQ',
        deliverQuotationFromOrder = 'deliverQuotationFromOrder',
        closeRFQ = 'closeRFQ',
        closeOrder = 'closeOrder',
        closeInvoice = 'closeInvoice',
        closePayment = 'closePayment',
        closePurchaseOrder = 'closePurchaseOrder',
        closeQuotation = 'closeQuotation',
        closeQuotationFromRFQ = 'closeQuotationFromRFQ',
        closeOrderFromRFQ = 'closeOrderFromRFQ',
        closeInvoiceFromRFQ = 'closeInvoiceFromRFQ',
        closePaymentFromRFQ = 'closePaymentFromRFQ',
        closePurchaseOrderFromRFQ = 'closePurchaseOrderFromRFQ',
        closeQuotationFromOrder = 'closeQuotationFromOrder',
        cancelRFQ = 'cancelRFQ',
        cancelOrder = 'cancelOrder',
        cancelInvoice = 'cancelInvoice',
        cancelPayment = 'cancelPayment',
        cancelPurchaseOrder = 'cancelPurchaseOrder',
        cancelQuotation = 'cancelQuotation',
        cancelQuotationFromRFQ = 'cancelQuotationFromRFQ',
        cancelOrderFromRFQ = 'cancelOrderFromRFQ',
        cancelInvoiceFromRFQ = 'cancelInvoiceFromRFQ',
        cancelPaymentFromRFQ = 'cancelPaymentFromRFQ',
        cancelPurchaseOrderFromRFQ = 'cancelPurchaseOrderFromRFQ',
        cancelQuotationFromOrder = 'cancelQuotationFromOrder',
        generateRFQ = 'generateRFQ',
        generateRFQFromOrder = 'generateRFQFromOrder',
        generateRFQFromInvoice = 'generateRFQFromInvoice',
        generateRFQFromPayment = 'generateRFQFromPayment',
        generateRFQFromPurchaseOrder = 'generateRFQFromPurchaseOrder',
        generateRFQFromQuotation = 'generateRFQFromQuotation',
        generateOrderFromQuotation = 'generateOrderFromQuotation',
        generateInvoiceFromQuotation = 'generateInvoiceFromQuotation',
        generatePurchaseOrderFromQuotation = 'generatePurchaseOrderFromQuotation',            
        generatePaymentFromQuotation = 'generatePaymentFromQuotation',

        updateCompanyProfile = 'updateCompanyProfile',
        updateSelfProfile = 'updateSelfProfile',
        viewCompanyProfile = 'viewCompanyProfile',
        viewSelfProfile = 'viewSelfProfile',
        createStatusTemplate = 'createStatusTemplate',
        updateStatusTemplate = 'updateStatusTemplate',
        deleteStatusTemplate = 'deleteStatusTemplate',
        viewStatusTemplate = 'viewStatusTemplate',
        createStatus = 'createStatus',
        updateStatus = 'updateStatus',
        deleteStatus = 'deleteStatus',
        viewStatus = 'viewStatus',

        createRole = 'createRole',
        updateRole = 'updateRole',
        deleteRole = 'deleteRole',
        viewRole = 'viewRole',

        createRFQ = 'createRFQ',
        viewRFQ = 'viewRFQ',

        createInvoice = 'createInvoice',
        viewInvoice = 'viewInvoice',

        createQuotation = 'createQuotation',
        viewQuotation = 'viewQuotation',
        
        createPurchaseOrder = 'createPurchaseOrder',
        viewPurchaseOrder = 'viewPurchaseOrder',

        createReceipt = 'createReceipt',
        viewReceipt = 'viewReceipt',
        // address
        createAddress = 'createAddress',
        updateAddress = 'updateAddress',
        deleteAddress = 'deleteAddress',
        viewAddress = 'viewAddress',

        viewWhiteLabel = 'viewWhiteLabel',

        //views
        // viewDashboard = 'viewDashboard',
        viewDocument = 'viewDocument',

        createOrder = 'createOrder',
        viewOrder = 'viewOrder',
        
        // order
        
}
    
