export  interface ProductList {
//   id: string,
  categoryId: string,
  productName: string,
//   sku: string,
//   seo?: string,
  subTitle?: string,
  prodoExclusive: boolean,
  greenProduct: boolean,
  description:JSON["stringify"],
  productImages: string,
//   price: number,
//   leadTime: string,
  moq: string,
  readyProduct: boolean,
  madeToOrder: boolean,
  whiteLabeling: boolean,
  protectionLevel: string,
  variants: [],
//   similarProductIds: [],
  
}